#ifndef PH_NXPBUILD_APP_H_INC
#define PH_NXPBUILD_APP_H_INC

/* PN5180, ISO profile, NFC-A polling and ISO-DEP. */
#define NXPRDLIB_REM_GEN_INTFS
#define NXPBUILD__PHHAL_HW_PN5180
#define NXPBUILD__PHNFCLIB
#define NXPBUILD__PHNFCLIB_PROFILES
#define NXPBUILD__PH_NFCLIB_ISO
#define NXPBUILD__PHAC_DISCLOOP_SW
#define NXPBUILD__PHAC_DISCLOOP_TYPEA_I3P3_TAGS
#define NXPBUILD__PHAC_DISCLOOP_TYPEA_I3P4_TAGS
#define NXPBUILD__PHPAL_I14443P3A_SW
#define NXPBUILD__PHPAL_I14443P4A_SW
#define NXPBUILD__PHPAL_I14443P4_SW

/* No MIFARE command helpers, KeyStore, Crypto, NFC-B/F/V or target mode. */
/* Select PH_OSAL_NULLOS or PH_OSAL_FREERTOS in compiler definitions. */
#endif
